name: Publish Poetry Docker image (Python 3.9)

on:
  push:
    branches:
      - main
    paths:
      - ../../Dockerfile39
      - requirements.txt
      - .github/workflows/deploy-3.9.yml
jobs:
  deploy:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          check-latest: true

      - name: Get Python version
        id: get-python-version
        run: |
          PYTHON_VERSION=$(python --version | awk '{print $2}')
          echo "PYTHON_VERSION=$PYTHON_VERSION" >> $GITHUB_ENV

      - name: Get Poetry version
        id: get-poetry-version
        run: |
          pip install -r requirements.txt
          POETRY_VERSION=$(poetry --version | awk '{print $3}' | sed 's/)$//')
          echo "POETRY_VERSION=$POETRY_VERSION" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACTIONS_GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            jnstockley/poetry
            ghcr.io/jnstockley/poetry

      - name: Build Docker image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile39
          platforms: linux/amd64,linux/arm64
          push: true
          tags: jnstockley/poetry:latest-python${{ env.PYTHON_VERSION }},jnstockley/poetry:${{ env.POETRY_VERSION }}-python${{ env.PYTHON_VERSION }}
          labels: ${{ steps.meta.outputs.labels }}
