name: Python 3.11

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile311
      - requirements.txt
      - .github/workflows/deploy-3.11.yml
jobs:
  deploy:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          check-latest: true

      - name: Get Python version
        id: get-python-version
        run: |
          PYTHON_VERSION=$(python --version | awk '{print $2}')
          echo "PYTHON_VERSION=$PYTHON_VERSION" >> $GITHUB_ENV

      - name: Get Poetry version
        id: get-poetry-version
        run: |
          pip install -r requirements.txt
          POETRY_VERSION=$(poetry --version | awk '{print $3}' | sed 's/)$//')
          echo "POETRY_VERSION=$POETRY_VERSION" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACTIONS_GITHUB_TOKEN }}

      - name: Generate RFC 3339 datetime
        id: generate-datetime
        run: |
          RFC3339_DATETIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "RFC3339_DATETIME=$RFC3339_DATETIME" >> $GITHUB_ENV

      - name: Extract metadata for pull request (testing)
        if: github.event_name == 'pull_request'
        run: |
          echo "tags=echo "tags=jnstockley/poetry:testing-python${{ env.PYTHON_VERSION }},jnstockley/poetry:testing-${{ env.POETRY_VERSION }}-python${{ env.PYTHON_VERSION }},ghcr.io/jnstockley/poetry:testing-python${{ env.PYTHON_VERSION }},ghcr.io/jnstockley/poetry:testing-${{ env.POETRY_VERSION }}-python${{ env.PYTHON_VERSION }}" >> $GITHUB_ENV" >> $GITHUB_ENV

      - name: Extract metadata for push (prod)
        if: github.event_name == 'push'
        run: |
          echo "tags=jnstockley/poetry:latest-python${{ env.PYTHON_VERSION }},jnstockley/poetry:${{ env.POETRY_VERSION }}-python${{ env.PYTHON_VERSION }},ghcr.io/jnstockley/poetry:latest-python${{ env.PYTHON_VERSION }},ghcr.io/jnstockley/poetry:${{ env.POETRY_VERSION }}-python${{ env.PYTHON_VERSION }}" >> $GITHUB_ENV

      - name: Build Docker image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile311
          platforms: linux/386,linux/amd64,linux/arm64
          push: true
          labels: |
            org.opencontainers.image.created=${{ env.RFC3339_DATETIME }}
            org.opencontainers.image.version=${{ env.POETRY_VERSION }}
            org.opencontainers.image.revision=${{ env.POETRY_VERSION }}-python${{ env.PYTHON_VERSION }}
            org.opencontainers.image.ref.name=${{ env.POETRY_VERSION }}
            org.opencontainers.image.description=Poetry ${{ env.POETRY_VERSION }} using Python ${{ env.PYTHON_VERSION }}
          tags: ${{ env.tags }}
